services:
  teamtalk-telegram-sender:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teamtalk-telegram-sender
    init: true
    volumes:
      - ./config.toml:/app/config.toml:ro
      - ./data:/app/data
    # Эта политика автоматически перезапустит контейнер после успешной установки SDK
    restart: unless-stopped
