"""Initial migration

Revision ID: 61f624ff8654
Revises:
Create Date: 2025-06-21 15:18:07.752386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '61f624ff8654'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_index(op.f('ix_admins_telegram_id'), 'admins', ['telegram_id'], unique=False)
    op.create_table('deeplinks',
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sa.Enum('SUBSCRIBE', 'UNSUBSCRIBE', name='deeplinkaction'), nullable=False),
    sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expected_telegram_id', sa.Integer(), nullable=True),
    sa.Column('expiry_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_deeplinks_token'), 'deeplinks', ['token'], unique=False)
    op.create_table('subscribed_users',
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_index(op.f('ix_subscribed_users_telegram_id'), 'subscribed_users', ['telegram_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notification_settings', sa.Enum('ALL', 'JOIN_OFF', 'LEAVE_OFF', 'NONE', name='notificationsetting'), nullable=False),
    sa.Column('muted_users', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mute_all', sa.Boolean(), nullable=False),
    sa.Column('teamtalk_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('not_on_online_enabled', sa.Boolean(), nullable=False),
    sa.Column('not_on_online_confirmed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_index(op.f('ix_user_settings_teamtalk_username'), 'user_settings', ['teamtalk_username'], unique=False)
    op.create_index(op.f('ix_user_settings_telegram_id'), 'user_settings', ['telegram_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_settings_telegram_id'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_teamtalk_username'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_subscribed_users_telegram_id'), table_name='subscribed_users')
    op.drop_table('subscribed_users')
    op.drop_index(op.f('ix_deeplinks_token'), table_name='deeplinks')
    op.drop_table('deeplinks')
    op.drop_index(op.f('ix_admins_telegram_id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
