"""create_muted_users_table

Revision ID: 91f46462bb8e
Revises: 61f624ff8654
Create Date: 2025-06-30 06:29:54.836533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91f46462bb8e'
down_revision: Union[str, Sequence[str], None] = '61f624ff8654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muted_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('muted_teamtalk_username', sa.String(), nullable=False),
    sa.Column('user_settings_telegram_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_settings_telegram_id'], ['user_settings.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_muted_users_muted_teamtalk_username'), 'muted_users', ['muted_teamtalk_username'], unique=False)
    op.drop_column('user_settings', 'muted_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('muted_users', sa.VARCHAR(), nullable=False))
    op.drop_index(op.f('ix_muted_users_muted_teamtalk_username'), table_name='muted_users')
    op.drop_table('muted_users')
    # ### end Alembic commands ###
