"""Add constraints to MutedUser and UserSettings

Revision ID: ffc2c9593dac
Revises: 8f587c1b4f53
Create Date: 2025-08-08 22:15:38.172450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffc2c9593dac'
down_revision: Union[str, Sequence[str], None] = '8f587c1b4f53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("muted_users", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "uq_user_muted_username",
            ["user_settings_telegram_id", "muted_teamtalk_username"],
        )

    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.create_check_constraint(
            "ck_user_settings_notification_valid",
            "notification_settings IN ('all', 'join_off', 'leave_off', 'none')",
        )
        batch_op.create_check_constraint(
            "ck_user_settings_mute_mode_valid",
            "mute_list_mode IN ('blacklist', 'whitelist')",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.drop_constraint("ck_user_settings_mute_mode_valid", type_="check")
        batch_op.drop_constraint(
            "ck_user_settings_notification_valid", type_="check"
        )

    with op.batch_alter_table("muted_users", schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_muted_username", type_="unique")
    # ### end Alembic commands ###
