MUTE_ACTION_MUTE = "mute"
MUTE_ACTION_UNMUTE = "unmute"

NOTIFICATION_EVENT_JOIN = "join"
NOTIFICATION_EVENT_LEAVE = "leave"

DEFAULT_LANGUAGE = "en"

TEAMTALK_PRIVATE_MESSAGE_TYPE = 1

INITIAL_LOGIN_IGNORE_DELAY_SECONDS = 2

RECONNECT_DELAY_SECONDS = 5
REJOIN_CHANNEL_DELAY_SECONDS = 2
REJOIN_CHANNEL_RETRY_SECONDS = 3
REJOIN_CHANNEL_MAX_ATTEMPTS = 3
REJOIN_CHANNEL_FAIL_WAIT_SECONDS = 20
TT_HELP_MESSAGE_PART_DELAY = 0.3
TT_MAX_MESSAGE_BYTES = 511

MIN_ARGS_FOR_ENV_PATH = 2

CALLBACK_NICKNAME_MAX_LENGTH = 30
USERS_PER_PAGE = 10 # For pagination in settings menus

LOG_FORMAT = "%(asctime)s - %(levelname)s - %(name)s - %(message)s"

DEFAULT_DATABASE_FILE = "bot_data.db"
DB_MAIN_NAME = "main"


WHO_CHANNEL_ID_ROOT = 1
WHO_CHANNEL_ID_SERVER_ROOT_ALT = 0 # Sometimes used for users not in a specific channel
WHO_CHANNEL_ID_SERVER_ROOT_ALT2 = -1 # Also seen for users not in a specific channel
